server:
  port: 8084
#Eureka
eureka:
  instance:
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MS-USER
          uri: http://172.26.192.1:8081
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthFilter
        - id: MS-RANKINGS
          uri: http://172.26.192.1:8083
          predicates:
            - Path=/api/v1/ranking/**
        - id: HOTEL-MS
          uri: http://172.26.192.1:8080
          predicates:
            - Path=/api/v1/hotel/**
        - id: AUTH-SERVICE
          uri: http://172.26.192.1:8086
          predicates:
            - Path=/auth/**