spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_db
    username: root
    password: AulaMatriz123
    driver: com.mysql.cj.jdbc.Driver
  application:
    name: ms-user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

springdoc:
  api-docs:
    path: /aulamatriz-doc
  show-actuator: false
  package-to-scan: com.ms.user.ms_user.controller

control:
  exception:
    business: Business exception
    system: System exception

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka